const test=require('node:test');const assert=require('node:assert/strict');const http=require('node:http');
const {MemoryRepository}=require('../src/repository/memoryRepository');const {createApp}=require('../src/app');const {createTestProviders}=require('../src/paymentService');
function request(server,method,path,body,token){return new Promise((resolve,reject)=>{const u=new URL(server.url);const h={'content-type':'application/json'};if(token)h.authorization=`Bearer ${token}`;const req=http.request({hostname:u.hostname,port:u.port,path,method,headers:h},r=>{let s='';r.on('data',c=>s+=c);r.on('end',()=>resolve({status:r.statusCode,body:s?JSON.parse(s):null}));});req.on('error',reject);if(body)req.write(JSON.stringify(body));req.end();});}
async function start(repo=new MemoryRepository()){const s=createApp(repo,createTestProviders());await new Promise(r=>s.listen(0,'127.0.0.1',r));s.url=`http://127.0.0.1:${s.address().port}`;return s;}
async function login(s,email='merchant@zandoconnect.test',password='MerchantV4!2026'){return (await request(s,'POST','/api/v1/auth/login',{email,password})).body.token;}
async function paidOrder(s,token){await request(s,'POST','/api/v1/cart/items',{productId:'prod-001',quantity:1},token);const o=await request(s,'POST','/api/v1/orders',{address:{city:'Kinshasa',street:'Rue A',phone:'0990000000'}},token);const p=await request(s,'POST','/api/v1/payments',{orderId:o.body.id,method:'card',provider:'demo_card',idempotencyKey:`v7-${Date.now()}-${Math.random()}`},token);await request(s,'POST',`/api/v1/payments/${p.body.id}/confirm`,null,token);return o.body;}
test('V9 health reports version 9.0.0',async()=>{const s=await start();const r=await request(s,'GET','/api/health');assert.equal(r.status,200);assert.equal(r.body.version,'9.0.0');s.close();});
test('pending order can be cancelled and stock is restored',async()=>{const repo=new MemoryRepository();const s=await start(repo);const token=await login(s);const before=(await repo.findProductById('prod-001')).stock;await request(s,'POST','/api/v1/cart/items',{productId:'prod-001',quantity:2},token);const o=await request(s,'POST','/api/v1/orders',{address:{city:'Kinshasa',street:'Rue A',phone:'0990000000'}},token);assert.equal((await repo.findProductById('prod-001')).stock,before-2);const c=await request(s,'POST',`/api/v1/orders/${o.body.id}/cancel`,null,token);assert.equal(c.status,200);assert.equal(c.body.status,'cancelled');assert.equal((await repo.findProductById('prod-001')).stock,before);s.close();});
test('customer creates delivery only after successful payment',async()=>{const s=await start();const token=await login(s);const o=await paidOrder(s,token);const d=await request(s,'POST',`/api/v1/orders/${o.id}/delivery`,null,token);assert.equal(d.status,201);assert.equal(d.body.status,'awaiting_merchant');assert.match(d.body.trackingCode,/^ZDO-/);const again=await request(s,'POST',`/api/v1/orders/${o.id}/delivery`,null,token);assert.equal(again.status,201);assert.equal(again.body.id,d.body.id);s.close();});
test('admin can prepare, assign and advance delivery',async()=>{const s=await start();const customerToken=await login(s);const o=await paidOrder(s,customerToken);const d=await request(s,'POST',`/api/v1/orders/${o.id}/delivery`,null,customerToken);const adminToken=await login(s,'admin@zandoconnect.test','AdminV4!2026');let r=await request(s,'POST',`/api/v1/admin/deliveries/${d.body.id}/status`,{status:'ready_for_pickup'},adminToken);assert.equal(r.status,200);r=await request(s,'POST',`/api/v1/admin/deliveries/${d.body.id}/assign`,{hubId:'hub-001',courierId:'courier-001'},adminToken);assert.equal(r.status,200);assert.equal(r.body.status,'courier_assigned');for(const status of ['picked_up','in_transit','out_for_delivery','delivered']){r=await request(s,'POST',`/api/v1/admin/deliveries/${d.body.id}/status`,{status},adminToken);assert.equal(r.status,200);assert.equal(r.body.status,status);}const events=await request(s,'GET',`/api/v1/deliveries/${d.body.id}/events`,null,customerToken);assert.equal(events.status,200);assert.ok(events.body.items.length>=7);s.close();});
test('invalid delivery transition is rejected',async()=>{const s=await start();const token=await login(s);const o=await paidOrder(s,token);const d=await request(s,'POST',`/api/v1/orders/${o.id}/delivery`,null,token);const admin=await login(s,'admin@zandoconnect.test','AdminV4!2026');const r=await request(s,'POST',`/api/v1/admin/deliveries/${d.body.id}/status`,{status:'delivered'},admin);assert.equal(r.status,409);s.close();});
