const test=require('node:test');const assert=require('node:assert/strict');const {createApp}=require('../src/app');const {MemoryRepository}=require('../src/repository/memoryRepository');
async function call(method,path,body,headers={}){const s=createApp(new MemoryRepository()).listen(0);await new Promise(r=>s.once('listening',r));try{return await fetch(`http://127.0.0.1:${s.address().port}${path}`,{method,headers:{'content-type':'application/json',...headers},body:body?JSON.stringify(body):undefined});}finally{await new Promise(r=>s.close(r));}}
async function token(){const r=await call('POST','/api/v1/auth/login',{email:'merchant@zandoconnect.test',password:'MerchantV4!2026'});return (await r.json()).token;}
test('merchant products require authentication',async()=>{assert.equal((await call('GET','/api/v1/merchant/merchant-001/products')).status,401);});
test('merchant can list own products',async()=>{const t=await token();const r=await call('GET','/api/v1/merchant/merchant-001/products',null,{authorization:`Bearer ${t}`});const b=await r.json();assert.equal(r.status,200);assert.equal(b.items.length,2);});
test('merchant can create valid product',async()=>{const t=await token();const r=await call('POST','/api/v1/merchant/merchant-001/products',{name:'Jean test',description:'Produit test',price:25,stock:8,categoryId:'cat-001'},{authorization:`Bearer ${t}`});const b=await r.json();assert.equal(r.status,201);assert.equal(b.name,'Jean test');assert.equal(b.stock,8);});
test('invalid price is rejected',async()=>{const t=await token();const r=await call('POST','/api/v1/merchant/merchant-001/products',{name:'Erreur',price:0,stock:2,categoryId:'cat-001'},{authorization:`Bearer ${t}`});assert.equal(r.status,400);});
test('merchant cannot edit another merchant product',async()=>{const t=await token();const r=await call('PATCH','/api/v1/merchant/merchant-001/products/prod-005',{name:'Hack',price:20,stock:1,categoryId:'cat-001'},{authorization:`Bearer ${t}`});assert.equal(r.status,403);});
test('merchant can delete own product',async()=>{const t=await token();const r=await call('DELETE','/api/v1/merchant/merchant-001/products/prod-001',null,{authorization:`Bearer ${t}`});assert.equal(r.status,204);});
