const test=require('node:test');
const assert=require('node:assert/strict');
const http=require('node:http');
const {MemoryRepository}=require('../src/repository/memoryRepository');
const {createApp}=require('../src/app');
const {createTestProviders}=require('../src/paymentService');
function request(server,method,path,body,token){return new Promise((resolve,reject)=>{const u=new URL(server.url);const headers={'content-type':'application/json'};if(token)headers.authorization=`Bearer ${token}`;const req=http.request({hostname:u.hostname,port:u.port,path,method,headers},r=>{let s='';r.on('data',c=>s+=c);r.on('end',()=>resolve({status:r.statusCode,body:s?JSON.parse(s):null}));});req.on('error',reject);if(body)req.write(JSON.stringify(body));req.end();});}
async function start(){const s=createApp(new MemoryRepository(),createTestProviders());await new Promise(r=>s.listen(0,'127.0.0.1',r));s.url=`http://127.0.0.1:${s.address().port}`;return s;}
async function login(s){return (await request(s,'POST','/api/v1/auth/login',{email:'merchant@zandoconnect.test',password:'MerchantV4!2026'})).body.token;}
test('payment requires authentication',async()=>{const s=await start();const r=await request(s,'POST','/api/v1/payments',{orderId:'x',method:'card',provider:'demo_card',idempotencyKey:'idem-123456'});assert.equal(r.status,401);s.close();});
test('payment is initialized and idempotent',async()=>{const s=await start();const token=await login(s);await request(s,'POST','/api/v1/cart/items',{productId:'prod-001',quantity:2},token);const o=await request(s,'POST','/api/v1/orders',{address:{city:'Kinshasa',street:'Rue A',phone:'0990000000'}},token);const input={orderId:o.body.id,method:'card',provider:'demo_card',idempotencyKey:'idem-123456'};const a=await request(s,'POST','/api/v1/payments',input,token);const b=await request(s,'POST','/api/v1/payments',input,token);assert.equal(a.status,201);assert.equal(a.body.status,'pending');assert.equal(b.body.id,a.body.id);s.close();});
test('successful payment confirms order',async()=>{const s=await start();const token=await login(s);await request(s,'POST','/api/v1/cart/items',{productId:'prod-001',quantity:1},token);const o=await request(s,'POST','/api/v1/orders',{address:{city:'Kinshasa',street:'Rue A',phone:'0990000000'}},token);const p=await request(s,'POST','/api/v1/payments',{orderId:o.body.id,method:'mobile_money',provider:'demo_mobile_money',idempotencyKey:'idem-confirm-1'},token);const c=await request(s,'POST',`/api/v1/payments/${p.body.id}/confirm`,null,token);assert.equal(c.status,200);assert.equal(c.body.status,'succeeded');const orders=await request(s,'GET','/api/v1/orders',null,token);assert.equal(orders.body.items[0].status,'confirmed');s.close();});
test('payment cannot be confirmed by another user',async()=>{const s=await start();const token=await login(s);await request(s,'POST','/api/v1/cart/items',{productId:'prod-001',quantity:1},token);const o=await request(s,'POST','/api/v1/orders',{address:{city:'Kinshasa',street:'Rue A',phone:'0990000000'}},token);const p=await request(s,'POST','/api/v1/payments',{orderId:o.body.id,method:'card',provider:'demo_card',idempotencyKey:'idem-owner-1'},token);const other=(await request(s,'POST','/api/v1/auth/register',{email:'other@example.com',password:'Password!123',name:'Other'})).body;const otherToken=(await request(s,'POST','/api/v1/auth/login',{email:'other@example.com',password:'Password!123'})).body.token;const r=await request(s,'POST',`/api/v1/payments/${p.body.id}/confirm`,null,otherToken);assert.equal(r.status,404);s.close();});
