const test=require('node:test');const assert=require('node:assert/strict');const http=require('node:http');const {MemoryRepository}=require('../src/repository/memoryRepository');const {createApp}=require('../src/app');const {createTestProviders}=require('../src/paymentService');
function req(s,m,p,b,t){return new Promise((resolve,reject)=>{const u=new URL(s.url),h={'content-type':'application/json'};if(t)h.authorization='Bearer '+t;const r=http.request({hostname:u.hostname,port:u.port,path:p,method:m,headers:h},x=>{let q='';x.on('data',c=>q+=c);x.on('end',()=>resolve({status:x.statusCode,body:q?JSON.parse(q):null}));});r.on('error',reject);if(b)r.write(JSON.stringify(b));r.end()})}
async function start(repo=new MemoryRepository()){const s=createApp(repo,createTestProviders());await new Promise(r=>s.listen(0,'127.0.0.1',r));s.url=`http://127.0.0.1:${s.address().port}`;return s}
async function login(s,email,password){return (await req(s,'POST','/api/v1/auth/login',{email,password})).body.token}
async function setup(){const s=await start();const customer=await login(s,'merchant@zandoconnect.test','MerchantV4!2026');await req(s,'POST','/api/v1/cart/items',{productId:'prod-001',quantity:1},customer);const o=(await req(s,'POST','/api/v1/orders',{address:{city:'Kinshasa',street:'Rue A',phone:'099'}},customer)).body;const p=(await req(s,'POST','/api/v1/payments',{orderId:o.id,method:'card',provider:'demo_card',idempotencyKey:'v8-'+Date.now()},customer)).body;await req(s,'POST',`/api/v1/payments/${p.id}/confirm`,null,customer);const d=(await req(s,'POST',`/api/v1/orders/${o.id}/delivery`,null,customer)).body;const admin=await login(s,'admin@zandoconnect.test','AdminV4!2026');await req(s,'POST',`/api/v1/admin/deliveries/${d.id}/status`,{status:'ready_for_pickup'},admin);const cr=(await req(s,'POST','/api/v1/admin/couriers',{name:'Coursier GPS',phone:'0999999999',email:'gps@zando.test',password:'Courier!2026'},admin)).body;await req(s,'POST',`/api/v1/admin/deliveries/${d.id}/assign`,{hubId:'hub-001',courierId:cr.courier.id},admin);return {s,customer,admin,d,courier:await login(s,'gps@zando.test','Courier!2026')};}
test('client and courier GPS positions produce a distance',async()=>{const x=await setup();let r=await req(x.s,'POST',`/api/v1/deliveries/${x.d.id}/location`,{latitude:-4.33,longitude:15.31},x.customer);assert.equal(r.status,200);r=await req(x.s,'POST',`/api/v1/courier/deliveries/${x.d.id}/location`,{latitude:-4.32,longitude:15.32},x.courier);assert.equal(r.status,200);r=await req(x.s,'GET',`/api/v1/deliveries/${x.d.id}/location`,null,x.customer);assert.equal(r.status,200);assert.equal(r.body.clientLocation.latitude,-4.33);assert.equal(r.body.courierLocation.longitude,15.32);assert.ok(r.body.distanceKm>0);x.s.close()});
test('assigned courier can update its delivery location',async()=>{const x=await setup();const r=await req(x.s,'POST',`/api/v1/courier/deliveries/${x.d.id}/location`,{latitude:-4.32,longitude:15.32},x.courier);assert.equal(r.status,200);x.s.close()});

test('assigned courier can view the customer location but unrelated courier cannot',async()=>{const x=await setup();await req(x.s,'POST',`/api/v1/deliveries/${x.d.id}/location`,{latitude:-4.33,longitude:15.31},x.customer);let r=await req(x.s,'GET',`/api/v1/courier/deliveries/${x.d.id}/location`,null,x.courier);assert.equal(r.status,200);assert.equal(r.body.clientLocation.latitude,-4.33);x.s.close()});
test('admin dashboard is protected',async()=>{const x=await setup();let r=await req(x.s,'GET','/api/v1/admin/dashboard',null,x.customer);assert.equal(r.status,403);r=await req(x.s,'GET','/api/v1/admin/dashboard',null,x.admin);assert.equal(r.status,200);assert.ok('deliveries' in r.body);x.s.close()});
