const test=require('node:test');
const assert=require('node:assert/strict');
const {createApp}=require('../src/app');
const {MemoryRepository}=require('../src/repository/memoryRepository');
async function call(method,path,body,headers={}){const s=createApp(new MemoryRepository()).listen(0);await new Promise(r=>s.once('listening',r));try{return await fetch(`http://127.0.0.1:${s.address().port}${path}`,{method,headers:{'content-type':'application/json',...headers},body:body?JSON.stringify(body):undefined});}finally{await new Promise(r=>s.close(r));}}
async function login(){const r=await call('POST','/api/v1/auth/login',{email:'merchant@zandoconnect.test',password:'MerchantV4!2026'});return r.json();}
test('register customer hashes password and returns public user',async()=>{const r=await call('POST','/api/v1/auth/register',{name:'Feli Test',email:'feli@example.com',password:'SecurePass!8'});const b=await r.json();assert.equal(r.status,201);assert.equal(b.user.role,'customer');assert.equal(b.user.email,'feli@example.com');assert.equal('passwordHash' in b.user,false);});
test('login returns signed token',async()=>{const b=await login();assert.ok(b.token);assert.equal(b.user.role,'merchant');});
test('me requires token',async()=>{assert.equal((await call('GET','/api/v1/auth/me')).status,401);const b=await login();const r=await call('GET','/api/v1/auth/me',null,{authorization:`Bearer ${b.token}`});assert.equal(r.status,200);assert.equal((await r.json()).user.merchantId,'merchant-001');});
test('merchant API rejects old dev header',async()=>{const r=await call('GET','/api/v1/merchant/merchant-001/products',null,{'x-merchant-id':'merchant-001'});assert.equal(r.status,401);});
test('merchant API accepts real session',async()=>{const b=await login();const r=await call('GET','/api/v1/merchant/merchant-001/products',null,{authorization:`Bearer ${b.token}`});assert.equal(r.status,200);});
test('merchant cannot manage another merchant',async()=>{const b=await login();const r=await call('GET','/api/v1/merchant/merchant-002/products',null,{authorization:`Bearer ${b.token}`});assert.equal(r.status,403);});
test('logout revokes token',async()=>{const repo=new MemoryRepository();const s=createApp(repo).listen(0);await new Promise(r=>s.once('listening',r));const base=`http://127.0.0.1:${s.address().port}`;try{let r=await fetch(`${base}/api/v1/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:'merchant@zandoconnect.test',password:'MerchantV4!2026'})});const b=await r.json();r=await fetch(`${base}/api/v1/auth/logout`,{method:'POST',headers:{authorization:`Bearer ${b.token}`}});assert.equal(r.status,204);r=await fetch(`${base}/api/v1/auth/me`,{headers:{authorization:`Bearer ${b.token}`}});assert.equal(r.status,401);}finally{await new Promise(r=>s.close(r));}});
test('merchant route is served',async()=>{const r=await call('GET','/merchant');assert.equal(r.status,200);assert.match(await r.text(),/Zando Connect/);});
