const test = require('node:test');
const assert = require('node:assert/strict');
const { MemoryRepository } = require('../src/repository/memoryRepository');
const { createApp } = require('../src/app');
const http = require('node:http');
function request(server, method, path, body, token){return new Promise((resolve,reject)=>{const u=new URL(server.url);const req=http.request({hostname:u.hostname,port:u.port,path,method,headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})}},r=>{let s='';r.on('data',c=>s+=c);r.on('end',()=>resolve({status:r.statusCode,body:s?JSON.parse(s):null}));});req.on('error',reject);if(body)req.write(JSON.stringify(body));req.end();});}
async function start(){const server=createApp(new MemoryRepository());await new Promise(r=>server.listen(0,'127.0.0.1',r));server.url=`http://127.0.0.1:${server.address().port}`;return server;}
async function login(server){return (await request(server,'POST','/api/v1/auth/login',{email:'merchant@zandoconnect.test',password:'MerchantV4!2026'})).body.token;}
test('cart requires authentication',async()=>{const s=await start();const r=await request(s,'GET','/api/v1/cart');assert.equal(r.status,401);s.close();});
test('authenticated user can add and remove cart item',async()=>{const s=await start();const token=await login(s);let r=await request(s,'POST','/api/v1/cart/items',{productId:'prod-001',quantity:2},token);assert.equal(r.status,200);assert.equal(r.body.items[0].quantity,2);r=await request(s,'DELETE','/api/v1/cart/items/prod-001',null,token);assert.equal(r.status,200);assert.equal(r.body.items.length,0);s.close();});
test('order consumes stock and clears cart',async()=>{const repo=new MemoryRepository();const s=createApp(repo);await new Promise(r=>s.listen(0,'127.0.0.1',r));s.url=`http://127.0.0.1:${s.address().port}`;const token=await login(s);const before=(await repo.findProductById('prod-001')).stock;await request(s,'POST','/api/v1/cart/items',{productId:'prod-001',quantity:3},token);const order=await request(s,'POST','/api/v1/orders',{address:{city:'Kinshasa',street:'Avenue exemple',phone:'+243900000000'}},token);assert.equal(order.status,201);assert.equal(order.body.total,85.5);assert.equal((await repo.findProductById('prod-001')).stock,before-3);assert.equal((await repo.getCart('user-merchant-001')).length,0);s.close();});
test('empty cart cannot create order',async()=>{const s=await start();const token=await login(s);const r=await request(s,'POST','/api/v1/orders',{address:{city:'Kinshasa',street:'Rue A',phone:'0990000000'}},token);assert.equal(r.status,400);s.close();});
