const crypto = require('node:crypto');
class PostgresRepository {
  constructor(pool) { this.pool = pool; }
  async listCategories(){ const {rows}=await this.pool.query('SELECT id,name,slug FROM categories ORDER BY name ASC'); return rows; }
  async listMerchants(){ const {rows}=await this.pool.query('SELECT id,name,slug,verified,city FROM merchants ORDER BY name ASC'); return rows; }
  async findMerchantById(id){ const {rows}=await this.pool.query('SELECT id,name,slug,verified,city,created_at AS "createdAt" FROM merchants WHERE id=$1',[id]); return rows[0]||null; }
  async findProductById(id){ const {rows}=await this.pool.query(`SELECT p.id,p.merchant_id AS "merchantId",p.category_id AS "categoryId",p.name,p.slug,p.description,p.price::float AS price,p.currency,p.stock,p.sales_count AS "salesCount",p.image_url AS "imageUrl",p.created_at AS "createdAt" FROM products p WHERE p.id=$1`,[id]); return rows[0]||null; }
  async findUserByEmail(email){ const {rows}=await this.pool.query('SELECT id,email,name,role,merchant_id AS "merchantId",courier_id AS "courierId",password_hash AS "passwordHash",created_at AS "createdAt" FROM users WHERE email=$1',[email]); return rows[0]||null; }
  async findUserById(id){ const {rows}=await this.pool.query('SELECT id,email,name,role,merchant_id AS "merchantId",courier_id AS "courierId",password_hash AS "passwordHash",created_at AS "createdAt" FROM users WHERE id=$1',[id]); return rows[0]||null; }
  async createUser(d){ const id=`user-${crypto.randomUUID()}`; const {rows}=await this.pool.query('INSERT INTO users(id,email,name,role,merchant_id,courier_id,password_hash) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,email,name,role,merchant_id AS "merchantId",courier_id AS "courierId",password_hash AS "passwordHash",created_at AS "createdAt"',[id,d.email,d.name,d.role,d.merchantId,d.courierId||null,d.passwordHash]); return rows[0]; }
  async createMerchant(d){ const id=`merchant-${crypto.randomUUID()}`; const slug=d.name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''); const {rows}=await this.pool.query('INSERT INTO merchants(id,name,slug,city) VALUES($1,$2,$3,$4) RETURNING id,name,slug,verified,city,created_at AS "createdAt"',[id,d.name,`${slug}-${id.slice(-6)}`,d.city]); return rows[0]; }
  async listMerchantProducts(merchantId){ const {rows}=await this.pool.query(`SELECT id,merchant_id AS "merchantId",category_id AS "categoryId",name,slug,description,price::float AS price,currency,stock,sales_count AS "salesCount",image_url AS "imageUrl",created_at AS "createdAt" FROM products WHERE merchant_id=$1 ORDER BY created_at DESC`,[merchantId]); return rows; }
  async createProduct(merchantId,d){ const id=`prod-${crypto.randomUUID()}`,slug=d.name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''); const {rows}=await this.pool.query(`INSERT INTO products(id,merchant_id,category_id,name,slug,description,price,currency,stock,image_url) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id,merchant_id AS "merchantId",category_id AS "categoryId",name,slug,description,price::float AS price,currency,stock,sales_count AS "salesCount",image_url AS "imageUrl",created_at AS "createdAt"`,[id,merchantId,d.categoryId,d.name,`${slug}-${id.slice(-6)}`,d.description,d.price,d.currency,d.stock,d.imageUrl]); return rows[0]; }
  async updateProduct(merchantId,id,d){ const {rows}=await this.pool.query(`UPDATE products SET name=$1,description=$2,price=$3,currency=$4,stock=$5,category_id=$6,image_url=$7 WHERE id=$8 AND merchant_id=$9 RETURNING id,merchant_id AS "merchantId",category_id AS "categoryId",name,slug,description,price::float AS price,currency,stock,sales_count AS "salesCount",image_url AS "imageUrl",created_at AS "createdAt"`,[d.name,d.description,d.price,d.currency,d.stock,d.categoryId,d.imageUrl,id,merchantId]); if(!rows[0]){const p=await this.findProductById(id);if(!p)throw Object.assign(new Error('Produit introuvable.'),{status:404});throw Object.assign(new Error('Accès refusé à ce produit.'),{status:403});} return rows[0]; }
  async deleteProduct(merchantId,id){ const r=await this.pool.query('DELETE FROM products WHERE id=$1 AND merchant_id=$2',[id,merchantId]); if(!r.rowCount){const p=await this.findProductById(id);if(!p)throw Object.assign(new Error('Produit introuvable.'),{status:404});throw Object.assign(new Error('Accès refusé à ce produit.'),{status:403});} }
  async findOrderByIdForUser(id,userId){const {rows}=await this.pool.query(`SELECT id,user_id AS "userId",status,currency,subtotal::float AS subtotal,delivery_fee::float AS "deliveryFee",tax_amount::float AS "taxAmount",total::float AS total,delivery_address AS "deliveryAddress",created_at AS "createdAt",updated_at AS "updatedAt" FROM orders WHERE id=$1 AND user_id=$2`,[id,userId]);return rows[0]||null;}
  async findPaymentByIdempotencyKey(userId,key){const {rows}=await this.pool.query(`SELECT id,order_id AS "orderId",user_id AS "userId",method,provider,status,amount::float AS amount,currency,provider_reference AS "providerReference",idempotency_key AS "idempotencyKey",metadata,created_at AS "createdAt",updated_at AS "updatedAt" FROM payments WHERE user_id=$1 AND idempotency_key=$2`,[userId,key]);return rows[0]||null;}
  async createPayment(d){const {rows}=await this.pool.query(`INSERT INTO payments(id,order_id,user_id,method,provider,status,amount,currency,provider_reference,idempotency_key,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id,order_id AS "orderId",user_id AS "userId",method,provider,status,amount::float AS amount,currency,provider_reference AS "providerReference",idempotency_key AS "idempotencyKey",metadata,created_at AS "createdAt",updated_at AS "updatedAt"`,[d.id,d.orderId,d.userId,d.method,d.provider,d.status,d.amount,d.currency,d.providerReference,d.idempotencyKey,JSON.stringify(d.metadata||{})]);return rows[0];}
  async findPaymentByIdForUser(id,userId){const {rows}=await this.pool.query(`SELECT id,order_id AS "orderId",user_id AS "userId",method,provider,status,amount::float AS amount,currency,provider_reference AS "providerReference",idempotency_key AS "idempotencyKey",metadata,created_at AS "createdAt",updated_at AS "updatedAt" FROM payments WHERE id=$1 AND user_id=$2`,[id,userId]);return rows[0]||null;}
  async updatePaymentStatus(id,status,providerReference,metadata){const client=await this.pool.connect();try{await client.query('BEGIN');const p=(await client.query(`UPDATE payments SET status=$1,provider_reference=COALESCE($2,provider_reference),metadata=$3,updated_at=NOW() WHERE id=$4 RETURNING id,order_id AS "orderId",user_id AS "userId",method,provider,status,amount::float AS amount,currency,provider_reference AS "providerReference",idempotency_key AS "idempotencyKey",metadata,created_at AS "createdAt",updated_at AS "updatedAt"`,[status,providerReference||null,JSON.stringify(metadata||{}),id])).rows[0];if(!p){await client.query('ROLLBACK');throw Object.assign(new Error('Paiement introuvable.'),{status:404});}if(status==='succeeded') await client.query(`UPDATE orders SET status='confirmed',updated_at=NOW() WHERE id=$1 AND status='pending'`,[p.orderId]);await client.query('COMMIT');return p;}catch(e){try{await client.query('ROLLBACK')}catch{}throw e;}finally{client.release();}}
  async cancelOrder(id,userId){const client=await this.pool.connect();try{await client.query('BEGIN');const order=(await client.query(`SELECT id,status FROM orders WHERE id=$1 AND user_id=$2 FOR UPDATE`,[id,userId])).rows[0];if(!order){throw Object.assign(new Error('Commande introuvable.'),{status:404});}if(order.status!=='pending')throw Object.assign(new Error('Seule une commande en attente peut être annulée.'),{status:409});const items=(await client.query(`SELECT product_id AS "productId",quantity FROM order_items WHERE order_id=$1`,[id])).rows;for(const i of items)await client.query('UPDATE products SET stock=stock+$1,sales_count=GREATEST(0,sales_count-$1) WHERE id=$2',[i.quantity,i.productId]);const {rows} = await client.query(`UPDATE orders SET status='cancelled',updated_at=NOW() WHERE id=$1 RETURNING id,user_id AS "userId",status,currency,subtotal::float AS subtotal,delivery_fee::float AS "deliveryFee",tax_amount::float AS "taxAmount",total::float AS total,delivery_address AS "deliveryAddress",created_at AS "createdAt",updated_at AS "updatedAt"`,[id]);await client.query('COMMIT');return rows[0];}catch(e){try{await client.query('ROLLBACK')}catch{}throw e;}finally{client.release();}}
  async findDeliveryByOrderId(orderId){const {rows}=await this.pool.query(`SELECT id,order_id AS "orderId",user_id AS "userId",status,tracking_code AS "trackingCode",hub_id AS "hubId",courier_id AS "courierId",client_latitude::float AS "clientLatitude",client_longitude::float AS "clientLongitude",courier_latitude::float AS "courierLatitude",courier_longitude::float AS "courierLongitude",location_updated_at AS "locationUpdatedAt",created_at AS "createdAt",updated_at AS "updatedAt" FROM deliveries WHERE order_id=$1`,[orderId]);return rows[0]||null;}
  async findDeliveryById(id){const {rows}=await this.pool.query(`SELECT id,order_id AS "orderId",user_id AS "userId",status,tracking_code AS "trackingCode",hub_id AS "hubId",courier_id AS "courierId",client_latitude::float AS "clientLatitude",client_longitude::float AS "clientLongitude",courier_latitude::float AS "courierLatitude",courier_longitude::float AS "courierLongitude",location_updated_at AS "locationUpdatedAt",created_at AS "createdAt",updated_at AS "updatedAt" FROM deliveries WHERE id=$1`,[id]);return rows[0]||null;}
  async findDeliveryByIdForUser(id,userId){const {rows}=await this.pool.query(`SELECT id,order_id AS "orderId",user_id AS "userId",status,tracking_code AS "trackingCode",hub_id AS "hubId",courier_id AS "courierId",client_latitude::float AS "clientLatitude",client_longitude::float AS "clientLongitude",courier_latitude::float AS "courierLatitude",courier_longitude::float AS "courierLongitude",location_updated_at AS "locationUpdatedAt",created_at AS "createdAt",updated_at AS "updatedAt" FROM deliveries WHERE id=$1 AND user_id=$2`,[id,userId]);return rows[0]||null;}
  async createDelivery(d){const {rows}=await this.pool.query(`INSERT INTO deliveries(id,order_id,user_id,status,tracking_code,hub_id,courier_id) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,order_id AS "orderId",user_id AS "userId",status,tracking_code AS "trackingCode",hub_id AS "hubId",courier_id AS "courierId",client_latitude::float AS "clientLatitude",client_longitude::float AS "clientLongitude",courier_latitude::float AS "courierLatitude",courier_longitude::float AS "courierLongitude",location_updated_at AS "locationUpdatedAt",created_at AS "createdAt",updated_at AS "updatedAt"`,[d.id,d.orderId,d.userId,d.status,d.trackingCode,d.hubId,d.courierId]);return rows[0];}
  async listDeliveriesForUser(userId){const {rows}=await this.pool.query(`SELECT id,order_id AS "orderId",user_id AS "userId",status,tracking_code AS "trackingCode",hub_id AS "hubId",courier_id AS "courierId",client_latitude::float AS "clientLatitude",client_longitude::float AS "clientLongitude",courier_latitude::float AS "courierLatitude",courier_longitude::float AS "courierLongitude",location_updated_at AS "locationUpdatedAt",created_at AS "createdAt",updated_at AS "updatedAt" FROM deliveries WHERE user_id=$1 ORDER BY created_at DESC`,[userId]);return rows;}
  async assignDelivery(id,hubId,courierId){const {rows}=await this.pool.query(`UPDATE deliveries SET hub_id=$1,courier_id=$2,status='courier_assigned',updated_at=NOW() WHERE id=$3 AND status='ready_for_pickup' RETURNING id,order_id AS "orderId",user_id AS "userId",status,tracking_code AS "trackingCode",hub_id AS "hubId",courier_id AS "courierId",client_latitude::float AS "clientLatitude",client_longitude::float AS "clientLongitude",courier_latitude::float AS "courierLatitude",courier_longitude::float AS "courierLongitude",location_updated_at AS "locationUpdatedAt",created_at AS "createdAt",updated_at AS "updatedAt"`,[hubId,courierId,id]);if(!rows[0])throw Object.assign(new Error('Livraison introuvable ou non prête.'),{status:409});return rows[0];}
  async updateDeliveryStatus(id,status){const {rows}=await this.pool.query(`UPDATE deliveries SET status=$1,updated_at=NOW() WHERE id=$2 RETURNING id,order_id AS "orderId",user_id AS "userId",status,tracking_code AS "trackingCode",hub_id AS "hubId",courier_id AS "courierId",client_latitude::float AS "clientLatitude",client_longitude::float AS "clientLongitude",courier_latitude::float AS "courierLatitude",courier_longitude::float AS "courierLongitude",location_updated_at AS "locationUpdatedAt",created_at AS "createdAt",updated_at AS "updatedAt"`,[status,id]);if(!rows[0])throw Object.assign(new Error('Livraison introuvable.'),{status:404});return rows[0];}
  async addDeliveryEvent(deliveryId,actor,status,note){const {rows}=await this.pool.query(`INSERT INTO delivery_events(id,delivery_id,actor,status,note) VALUES($1,$2,$3,$4,$5) RETURNING id,delivery_id AS "deliveryId",actor,status,note,created_at AS "createdAt"`,[`event-${crypto.randomUUID()}`,deliveryId,actor,status,note]);return rows[0];}
  async listDeliveryEvents(id){const {rows}=await this.pool.query(`SELECT id,delivery_id AS "deliveryId",actor,status,note,created_at AS "createdAt" FROM delivery_events WHERE delivery_id=$1 ORDER BY created_at ASC`,[id]);return rows;}
  async listHubs(){const {rows}=await this.pool.query(`SELECT id,name,city,active FROM hubs WHERE active=true ORDER BY name`);return rows;}
  async createCourier(d){const id=`courier-${crypto.randomUUID()}`;const {rows}=await this.pool.query(`INSERT INTO couriers(id,name,phone) VALUES($1,$2,$3) RETURNING id,name,phone,active,created_at AS "createdAt"`,[id,d.name,d.phone]);return rows[0];}
  async listCouriers(){const {rows}=await this.pool.query(`SELECT id,name,phone,active FROM couriers WHERE active=true ORDER BY name`);return rows;}

  async listAllOrders(){const orders=(await this.pool.query(`SELECT id,user_id AS "userId",status,currency,subtotal::float AS subtotal,delivery_fee::float AS "deliveryFee",tax_amount::float AS "taxAmount",total::float AS total,delivery_address AS "deliveryAddress",created_at AS "createdAt",updated_at AS "updatedAt" FROM orders ORDER BY created_at DESC`)).rows;for(const o of orders)o.items=(await this.pool.query(`SELECT product_id AS "productId",merchant_id AS "merchantId",product_name AS "productName",unit_price::float AS "unitPrice",quantity,line_total::float AS "lineTotal" FROM order_items WHERE order_id=$1`,[o.id])).rows;return orders;}
  async listAllPayments(){const {rows}=await this.pool.query(`SELECT id,order_id AS "orderId",user_id AS "userId",method,provider,status,amount::float AS amount,currency,created_at AS "createdAt" FROM payments ORDER BY created_at DESC`);return rows;}
  async findPaymentByProviderReference(ref){const {rows}=await this.pool.query(`SELECT id,order_id AS "orderId",user_id AS "userId",method,provider,status,amount::float AS amount,currency,provider_reference AS "providerReference",idempotency_key AS "idempotencyKey",metadata,created_at AS "createdAt",updated_at AS "updatedAt" FROM payments WHERE provider_reference=$1`,[ref]);return rows[0]||null;}
  async listPayments(userId){const {rows}=await this.pool.query(`SELECT id,order_id AS "orderId",user_id AS "userId",method,provider,status,amount::float AS amount,currency,provider_reference AS "providerReference",idempotency_key AS "idempotencyKey",metadata,created_at AS "createdAt",updated_at AS "updatedAt" FROM payments WHERE user_id=$1 ORDER BY created_at DESC`,[userId]);return rows;}

  async listProducts(filters = {}) {
    const values = [], where = [];
    const add = (sql, value) => { values.push(value); where.push(sql.replace('?', `$${values.length}`)); };
    if (filters.q) { values.push(`%${filters.q}%`, `%${filters.q}%`); where.push(`(p.name ILIKE $${values.length - 1} OR p.description ILIKE $${values.length})`); }
    if (filters.category) add('c.slug = ?', filters.category);
    if (filters.merchant) add('m.slug = ?', filters.merchant);
    if (filters.minPrice != null) add('p.price >= ?', filters.minPrice);
    if (filters.maxPrice != null) add('p.price <= ?', filters.maxPrice);
    if (filters.inStock) where.push('p.stock > 0');
    const order = { price_asc:'p.price ASC', price_desc:'p.price DESC', popular:'p.sales_count DESC', newest:'p.created_at DESC' }[filters.sort] || 'p.created_at DESC';
    const page = Math.max(1, Number(filters.page || 1));
    const limit = Math.min(50, Math.max(1, Number(filters.limit || 12)));
    const offset = (page - 1) * limit;
    const base = `FROM products p JOIN categories c ON c.id=p.category_id JOIN merchants m ON m.id=p.merchant_id ${where.length ? `WHERE ${where.join(' AND ')}` : ''}`;
    const data = await this.pool.query(`SELECT p.id,p.merchant_id AS "merchantId",p.category_id AS "categoryId",p.name,p.slug,p.description,p.price::float AS price,p.currency,p.stock,p.sales_count AS "salesCount",p.image_url AS "imageUrl",p.created_at AS "createdAt" ${base} ORDER BY ${order} LIMIT $${values.length + 1} OFFSET $${values.length + 2}`, [...values, limit, offset]);
    const count = await this.pool.query(`SELECT COUNT(*)::int AS total ${base}`, values);
    const total = count.rows[0].total;
    return { items:data.rows, total, page, limit, pages:Math.max(1, Math.ceil(total / limit)) };
  }

  async getCart(userId){const {rows}=await this.pool.query(`SELECT ci.product_id AS "productId",ci.quantity,p.id,p.merchant_id AS "merchantId",p.name,p.description,p.price::float AS price,p.currency,p.stock,p.sales_count AS "salesCount",p.image_url AS "imageUrl",p.category_id AS "categoryId",p.created_at AS "createdAt" FROM carts c JOIN cart_items ci ON ci.cart_id=c.id JOIN products p ON p.id=ci.product_id WHERE c.user_id=$1 ORDER BY ci.created_at ASC`,[userId]);return rows.map(r=>({productId:r.productId,quantity:r.quantity,product:r,lineTotal:Math.round(r.price*r.quantity*100)/100}));}
  async setCartItem(userId,productId,quantity){const product=await this.findProductById(productId);if(!product)throw Object.assign(new Error('Produit introuvable.'),{status:404});if(product.stock<quantity)throw Object.assign(new Error('Stock insuffisant.'),{status:409});const client=await this.pool.connect();try{await client.query('BEGIN');const cartId=(await client.query('SELECT id FROM carts WHERE user_id=$1',[userId])).rows[0]?.id||`cart-${crypto.randomUUID()}`;await client.query('INSERT INTO carts(id,user_id) VALUES($1,$2) ON CONFLICT(user_id) DO NOTHING',[cartId,userId]);const actual=(await client.query('SELECT id FROM carts WHERE user_id=$1',[userId])).rows[0].id;await client.query('INSERT INTO cart_items(cart_id,product_id,quantity) VALUES($1,$2,$3) ON CONFLICT(cart_id,product_id) DO UPDATE SET quantity=EXCLUDED.quantity',[actual,productId,quantity]);await client.query('UPDATE carts SET updated_at=NOW() WHERE id=$1',[actual]);await client.query('COMMIT');}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}return this.getCart(userId);}
  async removeCartItem(userId,productId){await this.pool.query('DELETE FROM cart_items ci USING carts c WHERE ci.cart_id=c.id AND c.user_id=$1 AND ci.product_id=$2',[userId,productId]);return this.getCart(userId);}
  async clearCart(userId){await this.pool.query('DELETE FROM cart_items ci USING carts c WHERE ci.cart_id=c.id AND c.user_id=$1',[userId]);}
  async createOrder(userId,address){const client=await this.pool.connect();try{await client.query('BEGIN');const cart=(await client.query(`SELECT ci.product_id AS "productId",ci.quantity,p.merchant_id AS "merchantId",p.name,p.price::float AS price,p.stock FROM carts c JOIN cart_items ci ON ci.cart_id=c.id JOIN products p ON p.id=ci.product_id WHERE c.user_id=$1 FOR UPDATE OF p`,[userId])).rows;if(!cart.length)throw Object.assign(new Error('Le panier est vide.'),{status:400});for(const i of cart)if(i.stock<i.quantity)throw Object.assign(new Error(`Stock insuffisant pour ${i.name}.`),{status:409});const subtotal=Math.round(cart.reduce((s,i)=>s+i.price*i.quantity,0)*100)/100,deliveryFee=0,taxAmount=0,total=subtotal,orderId=`order-${crypto.randomUUID()}`;const order=(await client.query(`INSERT INTO orders(id,user_id,status,currency,subtotal,delivery_fee,tax_amount,total,delivery_address) VALUES($1,$2,'pending','USD',$3,$4,$5,$6,$7) RETURNING id,user_id AS "userId",status,currency,subtotal::float AS subtotal,delivery_fee::float AS "deliveryFee",tax_amount::float AS "taxAmount",total::float AS total,delivery_address AS "deliveryAddress",created_at AS "createdAt",updated_at AS "updatedAt"`,[orderId,userId,subtotal,deliveryFee,taxAmount,total,JSON.stringify(address)])).rows[0];for(const i of cart){await client.query(`INSERT INTO order_items(id,order_id,product_id,merchant_id,product_name,unit_price,quantity,line_total) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[`item-${crypto.randomUUID()}`,orderId,i.productId,i.merchantId,i.name,i.price,i.quantity,i.price*i.quantity]);await client.query('UPDATE products SET stock=stock-$1,sales_count=sales_count+$1 WHERE id=$2',[i.quantity,i.productId]);}await client.query('DELETE FROM cart_items ci USING carts c WHERE ci.cart_id=c.id AND c.user_id=$1',[userId]);await client.query('COMMIT');return {...order,items:cart.map(i=>({productId:i.productId,merchantId:i.merchantId,productName:i.name,unitPrice:i.price,quantity:i.quantity,lineTotal:i.price*i.quantity}))};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
  async listOrders(userId){const orders=(await this.pool.query(`SELECT id,user_id AS "userId",status,currency,subtotal::float AS subtotal,delivery_fee::float AS "deliveryFee",tax_amount::float AS "taxAmount",total::float AS total,delivery_address AS "deliveryAddress",created_at AS "createdAt",updated_at AS "updatedAt" FROM orders WHERE user_id=$1 ORDER BY created_at DESC`,[userId])).rows;for(const o of orders)o.items=(await this.pool.query(`SELECT product_id AS "productId",merchant_id AS "merchantId",product_name AS "productName",unit_price::float AS "unitPrice",quantity,line_total::float AS "lineTotal" FROM order_items WHERE order_id=$1`,[o.id])).rows;return orders;}
  async updateDeliveryLocation(id,d){const {rows}=await this.pool.query(`UPDATE deliveries SET client_latitude=COALESCE($1,client_latitude),client_longitude=COALESCE($2,client_longitude),courier_latitude=COALESCE($3,courier_latitude),courier_longitude=COALESCE($4,courier_longitude),location_updated_at=NOW(),updated_at=NOW() WHERE id=$5 RETURNING id,order_id AS "orderId",user_id AS "userId",status,tracking_code AS "trackingCode",hub_id AS "hubId",courier_id AS "courierId",client_latitude::float AS "clientLatitude",client_longitude::float AS "clientLongitude",courier_latitude::float AS "courierLatitude",courier_longitude::float AS "courierLongitude",location_updated_at AS "locationUpdatedAt",created_at AS "createdAt",updated_at AS "updatedAt"`,[d.clientLatitude??null,d.clientLongitude??null,d.courierLatitude??null,d.courierLongitude??null,id]);if(!rows[0])throw Object.assign(new Error('Livraison introuvable.'),{status:404});return rows[0];}
  async listAdminDeliveries(){const {rows}=await this.pool.query(`SELECT id,order_id AS "orderId",user_id AS "userId",status,tracking_code AS "trackingCode",hub_id AS "hubId",courier_id AS "courierId",client_latitude::float AS "clientLatitude",client_longitude::float AS "clientLongitude",courier_latitude::float AS "courierLatitude",courier_longitude::float AS "courierLongitude",location_updated_at AS "locationUpdatedAt",created_at AS "createdAt",updated_at AS "updatedAt" FROM deliveries ORDER BY created_at DESC`);return rows;}
  async listUsers(){const {rows}=await this.pool.query(`SELECT id,email,name,role,merchant_id AS "merchantId",courier_id AS "courierId",created_at AS "createdAt" FROM users ORDER BY created_at DESC`);return rows;}
  async listCommissionRules(){const {rows}=await this.pool.query(`SELECT id,category_id AS "categoryId",rate_percent::float AS "ratePercent",active,created_at AS "createdAt" FROM commission_rules WHERE active=true ORDER BY created_at DESC`);return rows;}
  async createCommissionRule(d){const id=`rule-${crypto.randomUUID()}`;const {rows}=await this.pool.query(`INSERT INTO commission_rules(id,category_id,rate_percent,active) VALUES($1,$2,$3,$4) RETURNING id,category_id AS "categoryId",rate_percent::float AS "ratePercent",active,created_at AS "createdAt"`,[id,d.categoryId||null,d.ratePercent,d.active!==false]);return rows[0];}
  async listOrderCommissions(){const {rows}=await this.pool.query(`SELECT id,order_id AS "orderId",merchant_id AS "merchantId",gross_amount::float AS "grossAmount",commission_amount::float AS "commissionAmount",merchant_net_amount::float AS "merchantNetAmount",created_at AS "createdAt" FROM order_commissions ORDER BY created_at DESC`);return rows;}

  async createNotification(d){const id=`notif-${crypto.randomUUID()}`;const {rows}=await this.pool.query(`INSERT INTO notifications(id,user_id,type,title,message,metadata) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,user_id AS "userId",type,title,message,metadata,read_at AS "readAt",created_at AS "createdAt"`,[id,d.userId,d.type,d.title,d.message,JSON.stringify(d.metadata||{})]);return rows[0];}
  async listNotifications(userId){const {rows}=await this.pool.query(`SELECT id,user_id AS "userId",type,title,message,metadata,read_at AS "readAt",created_at AS "createdAt" FROM notifications WHERE user_id=$1 ORDER BY created_at DESC`,[userId]);return rows;}
  async markNotificationRead(id,userId){const {rows}=await this.pool.query(`UPDATE notifications SET read_at=NOW() WHERE id=$1 AND user_id=$2 RETURNING id,user_id AS "userId",type,title,message,metadata,read_at AS "readAt",created_at AS "createdAt"`,[id,userId]);if(!rows[0])throw Object.assign(new Error('Notification introuvable.'),{status:404});return rows[0];}
  async createAuditLog(d){const id=`audit-${crypto.randomUUID()}`;const {rows}=await this.pool.query(`INSERT INTO audit_logs(id,actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,actor_user_id AS "actorUserId",action,entity_type AS "entityType",entity_id AS "entityId",metadata,created_at AS "createdAt"`,[id,d.actorUserId||null,d.action,d.entityType,d.entityId||null,JSON.stringify(d.metadata||{})]);return rows[0];}
  async listAuditLogs(){const {rows}=await this.pool.query(`SELECT id,actor_user_id AS "actorUserId",action,entity_type AS "entityType",entity_id AS "entityId",metadata,created_at AS "createdAt" FROM audit_logs ORDER BY created_at DESC`);return rows;}

}
module.exports={PostgresRepository};
